
#include <Uefi.h>
#include <Library/IoLib.h>
#include <Library/DebugLib.h>
#include <PlatformDefinition.h>




#define SB_IDE_SATA_DEVICE_ID         0x0571
#define SB_IDE_LPC_DEVICE_ID          0x3227


VOID
PatchSataIdeDevIdForLinux (
  VOID
  )
{
  UINT16 LpcVId;

  LpcVId = MmioRead16(LPC_PCI_REG(PCI_VID_REG));
  MmioWrite32(LPC_PCI_REG(LPC_PCIID_BACKDOOR_REG), (SB_IDE_LPC_DEVICE_ID<<16)|LpcVId);
  MmioOr8(LPC_PCI_REG(LPC_PNP_TEST_MODE2_REG), LPC_PCIID_PROGRAM_EN);
  MmioWrite32(LPC_PCI_REG(LPC_SVID_BACKDOOR_REG), (SB_IDE_LPC_DEVICE_ID<<16)|LpcVId);
  //MmioWrite16(SATA_PCI_REG(SATA_SSID_BACKDOOR_IDE_REG), SB_IDE_SATA_DEVICE_ID);		


}

VOID UpdateLpcSsid()
{
  MmioWrite32(LPC_PCI_REG(LPC_SVID_BACKDOOR_REG), MmioRead32(LPC_PCI_REG(PCI_VID_REG)));
}


// SATA IDE Device ID and LPC Device ID are used to patch linux installation
// DO NOT MODIFY IT.
VOID UpdateSsid(VOID)
{
  MmioWrite32(HC_PCI_REG(PCI_SSID_REG),  MmioRead32(HC_PCI_REG(PCI_VID_REG)));
  MmioWrite32(ERRRPT_PCI_REG(PCI_SSID_REG), MmioRead32(ERRRPT_PCI_REG(PCI_VID_REG)));
  MmioWrite32(HIF_PCI_REG(PCI_SSID_REG),  MmioRead32(HIF_PCI_REG(PCI_VID_REG)));   
  MmioWrite32(DRAM_PCI_REG(PCI_SSID_REG),  MmioRead32(DRAM_PCI_REG(PCI_VID_REG)));
  MmioWrite32(NPMC_PCI_REG(PCI_SSID_REG),  MmioRead32(NPMC_PCI_REG(PCI_VID_REG)));
  MmioWrite32(APIC_PCI_REG(PCI_SSID_REG),  MmioRead32(APIC_PCI_REG(PCI_VID_REG)));
  MmioWrite32(SCRCH_PCI_REG(PCI_SSID_REG), MmioRead32(SCRCH_PCI_REG(PCI_VID_REG)));
  MmioWrite32(RAIDA1_PCI_REG(PCI_SSID_REG), MmioRead32(RAIDA1_PCI_REG(PCI_VID_REG)));

//HYL-20160916-start
//PCI UART
  MmioOr8(UART0_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), D10F0F3_SVIDEN);
  MmioOr8(UART0_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), D10F0F3_SSIDEN);
  MmioWrite32(UART0_PCI_REG(PCI_SSID_REG), MmioRead32(UART0_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(UART0_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), (UINT8)~D10F0F3_SVIDEN);
  MmioAnd8(UART0_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), (UINT8)~D10F0F3_SSIDEN);
  MmioOr8(UART1_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), D10F0F3_SVIDEN);
  MmioOr8(UART1_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), D10F0F3_SSIDEN);
  MmioWrite32(UART1_PCI_REG(PCI_SSID_REG), MmioRead32(UART1_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(UART1_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), (UINT8)~D10F0F3_SVIDEN);
  MmioAnd8(UART1_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), (UINT8)~D10F0F3_SSIDEN);
  MmioOr8(UART2_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), D10F0F3_SVIDEN);
  MmioOr8(UART2_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), D10F0F3_SSIDEN);
  MmioWrite32(UART2_PCI_REG(PCI_SSID_REG), MmioRead32(UART2_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(UART2_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), (UINT8)~D10F0F3_SVIDEN);
  MmioAnd8(UART2_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), (UINT8)~D10F0F3_SSIDEN);
  MmioOr8(UART3_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), D10F0F3_SVIDEN);
  MmioOr8(UART3_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), D10F0F3_SSIDEN);
  MmioWrite32(UART3_PCI_REG(PCI_SSID_REG), MmioRead32(UART3_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(UART3_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), (UINT8)~D10F0F3_SVIDEN);
  MmioAnd8(UART3_PCI_REG(D10F0F3_BACK_DOOR_CTL_REG), (UINT8)~D10F0F3_SSIDEN);  
//eSPI
  MmioOr8(ESPI_PCI_REG(D11F0_BACK_DOOR_ENABLE_Z1), D11F0_EN2CW_Z1);
  MmioWrite32(ESPI_PCI_REG(PCI_SSID_REG), MmioRead32(ESPI_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(ESPI_PCI_REG(D11F0_BACK_DOOR_ENABLE_Z1), (UINT8)~D11F0_EN2CW_Z1);
//LPC
  MmioWrite32(LPC_PCI_REG(LPC_SVID_BACKDOOR_REG), MmioRead32(LPC_PCI_REG(PCI_VID_REG)));
//HYL-20160916-end    

  MmioWrite32(SNMIC_PCI_REG(SNMIC_SSID_BACKDOOR_REG), MmioRead32(SNMIC_PCI_REG(PCI_VID_REG)));
  MmioOr8(SNMIC_PCI_REG(SNMIC_PCI_IO_CYCLE_CTRL_REG), SNMIC_RX2C_SEL);

// UHCI 0 ~ 2
  //MmioOr8(UHCI_PCI_REG(0, USB_SSID_BDEN_REG), USB_SSID_BDEN);
  //MmioWrite32(UHCI_PCI_REG(0, PCI_SSID_REG),  MmioRead32(UHCI_PCI_REG(0, PCI_VID_REG)));
  //MmioAnd8(UHCI_PCI_REG(0, USB_SSID_BDEN_REG), (UINT8)~USB_SSID_BDEN); 

  //MmioOr8(UHCI_PCI_REG(1, USB_SSID_BDEN_REG), USB_SSID_BDEN);
  //MmioWrite32(UHCI_PCI_REG(1, PCI_SSID_REG),  MmioRead32(UHCI_PCI_REG(1, PCI_VID_REG)));
  //MmioAnd8(UHCI_PCI_REG(1, USB_SSID_BDEN_REG), (UINT8)~USB_SSID_BDEN); 

  //MmioOr8(UHCI_PCI_REG(2, USB_SSID_BDEN_REG), USB_SSID_BDEN);
  //MmioWrite32(UHCI_PCI_REG(2, PCI_SSID_REG),  MmioRead32(UHCI_PCI_REG(2, PCI_VID_REG)));
  //MmioAnd8(UHCI_PCI_REG(2, USB_SSID_BDEN_REG), (UINT8)~USB_SSID_BDEN); 

// EHCI
  //MmioOr8(EHCI_PCI_REG(USB_SSID_BDEN_REG), USB_SSID_BDEN);
  //MmioWrite32(EHCI_PCI_REG(PCI_SSID_REG),  MmioRead32(EHCI_PCI_REG(PCI_VID_REG)));
  //MmioAnd8(EHCI_PCI_REG(USB_SSID_BDEN_REG), (UINT8)~USB_SSID_BDEN); 

// HDAC
#ifndef	CHX001_HAPS //HYL-20160916
  MmioOr8(HDAC_PCI_REG(HDAC_SSID_BACKDOOR_EN_REG), HDAC_SSID_BACKDOOR_EN);
  MmioWrite32(HDAC_PCI_REG(PCI_SSID_REG), MmioRead32(HDAC_PCI_REG(PCI_VID_REG)));  
  MmioAnd8(HDAC_PCI_REG(HDAC_SSID_BACKDOOR_EN_REG), (UINT8)~HDAC_SSID_BACKDOOR_EN);  
#endif  //HYL-20160916  
}


