// FILE AUTO GENERATED BY Win32Tool.exe, DO NOT EDIT...
#ifndef __BUILD_DATE_TIME_H__   
#define __BUILD_DATE_TIME_H__   

#define TKN_BUILD_YEAR      2016
#define TKN_BUILD_MONTH     10
#define TKN_BUILD_DAY       19
#define TKN_BUILD_HOUR      17
#define TKN_BUILD_MINUTE    39
#define TKN_BUILD_SECOND    00
#define TKN_BUILD_TIME_STR     "2016-10-19 17:39"
#define TKN_BUILD_RLSDATE_STR  "10/19/2016"

#endif   

