// FILE AUTO GENERATED BY make.cmd, DO NOT EDIT... 
#ifndef __BIOS_NAME_H__          
#define __BIOS_NAME_H__          
                                 
#define TKN_BIOS_MAJOR_VER  06 
#define TKN_BIOS_MINOR_VER  03 
#define TKN_BIOS_VER        0603 
#define TKN_BIOSID_NAME     HX001EA1_10_D0603 
#define TKN_BOARD_ID        HX001EA1 
#define TKN_OEM_ID          CRB 
                                 
#endif                           
                                 
